services:

  mariadb: # Our DB server
    build: ./mariadb #Dockerfile path: build image from your Dockerfile which is here
    container_name: mariadb
    env_file: .env
    restart: always
    volumes: #Where DB stores data
      - mariadb_data:/var/lib/mysql
    networks: # Allows communication with WordPress
      - inception_network

  wordpress: # Our Application
    build: ./wordpress
    container_name: wordpress
    env_file: .env
    depends_on: #mariadb will start first
      - mariadb
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on: #wordpress will start first
      - wordpress 
    restart: always
    ports:
      - "443:443" #HTTPS, entrypoint from the internet
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network

networks:
  inception_network: #private network for containers to talk with each other

volumes: #makes sure data survives when container restarts
  mariadb_data:
  wordpress_data: