# NGINX web server
#   It recerives HTTP requests and serves web content
#
# NGINX does NOT understand PHP (WordPress).
#
#       Browser
#         ↓
#       nginx (handles HTTP)
#         ↓
#       php-fpm (executes PHP)
#         ↓
#       WordPress
#         ↓
#       MariaDB
#
server {

    # Listens on port 443 (HTTPS)
    listen 443 ssl; 

    # Domain name
    server_name uxmancis.42.fr;

    # SSL certificates: files used to encrypt HTTPS traffic
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Root directory: where website lives live
    root /var/www/html;

    # Default files: 
    #   When user goes to https://uxmancis.42.fr/, then
    #   WordPress uses index.php
    index index.php index.html;

    # PHP handling:
    #      Sends PHP request to:
    #           host= wordpress (container name)
    #           port= 9000   
    location ~ \.php$ {
        include fastcgi_params;

        # Connect to PHP
        fastcgi_pass wordpress:9000;

        # Tell php-fpm what file to execute
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}